# https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy
name: Render
on:
  push:
    branches:
      - main

jobs:

  render:

    runs-on: ubuntu-latest

    permissions:

      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"

    - name: Deploy GitHub Pages
      run: |
        make html
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../_build/html/* .
        rm README.html
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
